name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.2' # Define the OTP version [required]
        
    - name: Cache hex deps
      uses: actions/cache@v2
      env:
        cache-name: cache-hex-deps
      with:
        path: ./deps
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('mix.lock') }}
        
    - name: Install Dependencies
      run: mix deps.get
      
    - name: Run Tests
      run: mix test
